# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00dd332b563c1b8037922adca134b90185b07314e416be155c448e5d76cda0a789b2652dfa6fa18297473a1fe1ce23abba169c0b08ea4c1f293ef51b8443bc06

test:
  secret_key_base: 0e8a01ebc5aa8f07de61cc4ee8ca3741941a4e42f93e20dd01a92b616cfe4435481fb2d9352f9c27376055dfef3b584d13a733ea4804c69ec11c6e7b71174be4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
